# coding=utf-8
# 原文：https://blog.csdn.net/xiaoquantouer/article/details/75089200
# 版权声明：本文为博主原创文章，转载请附上博文链接！

import unittest
from test_mathfunc import TestMathFunc
from HTMLTestRunner import HTMLTestRunner

if __name__ == '__main__':
    suite = unittest.TestSuite()

    tests = [TestMathFunc("test_add"), TestMathFunc("test_minus"), TestMathFunc("test_divide")]
    suite.addTests(tests)

    '''目录下生成了'UnittestTextReport.txt，所有的执行报告均输出到了此文件中'''
    # with open('UnittestTextReport.txt', 'a') as  f:
    #     runner = unittest.TextTestRunner(stream=f, verbosity=2)
    #     runner.run(suite)

    '''借助HTMLTestRunner生成HTML报告,下载地址：http://tungwaiyip.info/software/HTMLTestRunner.html'''
    with open('HTMLReport.html', 'wb+') as f:
        runner = HTMLTestRunner(stream=f,
                                title = 'MathFunc Test Report',
                                description='generated by HTMLTestRunner.',
                                verbosity=2
                                )
        runner.run(suite)
